config/routes.rb
Bibapp::Application.routes.draw do


  def make_routes
    resources :works do
      collection do
        get :auto_complete_for_author_string
        get :auto_complete_for_editor_string
        get :auto_complete_for_keyword_name
        get :auto_complete_for_publication_name
        get :auto_complete_for_publisher_name
        get :auto_complete_for_tag_name
        get :orphans
        delete :destroy_multiple
        #Following support legacy RJS stuff
        post :reorder_list
        post :add_item_to_list
        post :remove_item_from_list
        post :add_author_to_list
        post :remove_author_from_list
        post :add_contributor_to_list
        post :remove_contributor_from_list
        post :orphans_delete
      end
      member do
        get :merge_duplicates
        get :add_to_saved
        get :remove_from_saved
        put :change_type
      end

      resources :attachments
    end

    #####
    # Person routes
    #####
    resources :people do
      collection do
        get :batch_csv_show
        post :batch_csv_create
      end
      resources :attachments
      resources :works
      resources :groups
      resources :pen_names
      resources :memberships
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Group routes
    #####
    # Add Auto-Complete routes for adding new groups
    resources :groups do
      collection do
        get :auto_complete_for_group_name
        get :hidden
      end
      member do
        get :hide
        get :unhide
      end
      resources :works
      resources :people
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Membership routes
    #####
    # Add Auto-Complete routes
    resources :memberships do
      collection do
        get :auto_complete_for_group_name
        put :create_multiple
        post :sort
        post :search_groups
      end
    end

    #####
    # Contributorship routes
    #####
    resources :contributorships do
      collection do
        get :admin
        get :archivable
        put :act_on_multiple
      end

      member do
        put :verify
        put :deny
      end
    end
    #####
    # Publisher routes
    #####
    resources :publishers do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    #####
    # Publication routes
    #####
    resources :publications do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    ####
    # User routes
    ####
    # Make URLs like /user/1/password/edit for Users managing their passwords
    resources :users do
      resources :imports
      resource :password
      collection do
        match 'activate(/:activation_code)', :to => 'users#activate', :as => 'activate'
      end
      member do
        get :update_email
        post :request_update_email
      end
    end

    ####
    # Import routes
    ####
    resources :imports do
      resource :user
      resources :attachments
    end

    ####
    # Search route
    ####
    match 'search', :to => 'search#index', :as => 'search'
    match 'search/advanced', :to => 'search#advanced', :as => 'advanced_search'

    ####
    # Saved routes
    ####
    match 'saved', :to => 'user_sessions#saved', :as => 'saved'
    match 'sessions/delete_saved', :to => 'user_sessions#delete_saved',
          :as => 'delete_saved'
    match 'sessions/add_many_to_saved', :to => 'user_sessions#add_many_to_saved',
          :as => 'add_many_to_saved'
    ####
    # Authentication routes
    ####
    # Make easier routes for authentication (via restful_authentication)
    match 'signup', :to => 'users#new', :as => 'signup'
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'activate/:activation_code', :to => 'users#activate', :as => 'activate'

    ####
    # DEFAULT ROUTES
    ####
    # Install the default routes as the lowest priority.
    resources :name_strings
    resources :memberships
    resources :pen_names do
      collection do
        post :create_name_string
        post :live_search_for_name_strings
        post :sort
      end
    end
    resources :keywords
    resources :keywordings
    resources :passwords
    resources :attachments do
      collection do
        post :add_upload_box
      end
    end

    # Default homepage to works index action
    root :to => 'works#index'

    match 'citations', :to => 'works#index'

    resource :user_session

    resources :authentications
    match '/auth/:provider/callback' => 'authentications#create'
    match '/admin/index' => "admin#index"
    match 'admin/duplicates' => "admin#duplicates"
    match 'admin/ready_to_archive' => "admin#ready_to_archive"
    match 'admin/update_sherpa_data' => "admin#update_sherpa_data"
    match 'admin/deposit_via_sword' => "admin#deposit_via_sword"
    match 'admin/update_publishers_from_sherpa' => "admin#update_publishers_from_sherpa"

    match 'roles/index' => "roles#index"
    match 'roles/destroy' => "roles#destroy"
    match 'roles/create' => "roles#create"
    match 'roles/new_admin' => "roles#new_admin"
    match 'roles/new_editor' => "roles#new_editor"
  end

  if I18n.available_locales.many?
    locale_regexp = Regexp.new(I18n.available_locales.join('|'))
    scope "(:locale)", :locale => locale_regexp do
      make_routes
    end
    #uncomment to make multi-locale version able to direct locale-less routes as well
    #make_routes
  else
    make_routes
  end


end

app/models/membership.rb
require 'solr_updater'
class Membership < ActiveRecord::Base
  include SolrUpdater
  belongs_to :person
  belongs_to :group

  #No duplicate memberships, please
  validates_uniqueness_of :person_id, :scope => :group_id

  html_fragment :title, :scrub => :escape

  acts_as_list  :scope => :person

  scope :active, where("end_date is ?", nil)

  def get_associated_works
    self.person.works.verified
  end

  def require_reindex?
    self.changed?
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  #Require a user be logged in to create / update / destroy
  before_filter :login_required, :only => [:new, :create, :edit, :update, :destroy]

  before_filter :find_membership, :only => [:destroy]
  before_filter :find_person, :only => [:create, :create_group, :new, :destroy, :sort, :ajax_sort]
  before_filter :find_group, :only => [:create, :create_group, :destroy]

  make_resourceful do
    build :index, :show, :new, :update

    before :update do
      #'editor' of person or group can update membership details
      permit "editor of person or group"
    end

    before :new do
      @person = Person.find(params[:person_id])
      @title = t('common.memberships.new_title', :name => @person.display_name)

      member = @person.groups.empty? ? "non_member" : "member"
      @status = params[:status] || member

      #For searching groups: AND together like conditions on all pieces of the query
      @query = params[:q]
      rails_query = Group.order_by_name
      if @query
        query_words = @query.downcase.split
        query_words.each do |qw|
          rails_query = rails_query.where("LOWER(name) LIKE ?", "%#{qw}%")
        end
      end
      results = rails_query

      @parents = Array.new
      @groups = Array.new

      # 'results' contains a list of all groups, or all groups returned by the
      # search. We now form two arrays, one for top-level parents, the other
      # for all groups. We will paginate on top-level parents.
      #
      # For each group, check to see if it is a parent:
      # If it has no parents, then it is a parent by default (even if childless)
      # and it goes into the @parents array.
      # If it has a parent, then the parent goes into the @parents array,
      # unless the parent has parents, in which case it is not top-level.
      #
      # Regardless of parent status, all groups go into the @groups array
      # as well as their parent and all their children. That way, if a group
      # with a parent or with children is retrieved from a search, it's parent
      # and children will be returned as well.

      results.each do |g|
        @parents << g.top_level_parent
        @groups << g.ancestors_and_descendants
        @groups << g
      end

      @groups = @groups.flatten.uniq
      @parents.uniq!

      @groups.sort! { |a, b| a.name.downcase <=> b.name.downcase }
      @parents.sort! { |a, b| a.name.downcase <=> b.name.downcase }

    end

  end


  def create
    #'editor' of person or group can create a membership
    permit "editor of person or group"

    @person.groups << @group
    respond_to do |format|
      format.html { redirect_to new_person_membership_path(:person_id => @person.id) }
    end
  end


  def create_multiple

    person = Person.find(params[:person_id])
    group_ids = params[:group_id]

    full_success = true

    unless group_ids.blank?
      #Create each membership one by one, so we can be sure user has 'edit' rights on all
      group_ids.each do |group_id|
        group = Group.find(group_id)

        #One final check...only an editor on this person or group can create the membership
        if logged_in? && (current_user.has_role?("editor", person) || current_user.has_role?("editor", group))
          begin
            person.groups << group
          rescue ActiveRecord::RecordInvalid
            flash[:warning] = t('common.memberships.flash_create_multiple_membership')
          end
        else
          full_success = false
        end
      end
    end

    #Return path for any actions that take place on the memberships page
    return_path = new_person_membership_path(:person_id=>params[:person_id],
                                             :status=>full_success ? 'member' : params[:status])

    respond_to do |format|
      if full_success
        flash[:notice] = t('common.memberships.flash_create_multiple_success')
      else
        flash[:warning] = t('common.memberships.flash_create_multiple_privileges')
      end
      #forward back to path which was specified in params
      format.html { redirect_to return_path }
      format.xml { head :ok }
    end
  end

  def create_group
    #'editor' of person can create new groups
    permit "editor of person"

    @group = Group.find_or_create_by_name(params[:group][:name])
    @group.hide = false
    @group.save

    @membership = Membership.find_by_person_id_and_group_id(@person.id, @group.id)
    unless @membership
      @person.groups << @group
      respond_to do |format|
        format.html { redirect_to new_person_membership_path(:person_id => @person.id) }
      end
    end
  end

  def search_groups
    respond_to do |format|
      format.html { redirect_to new_person_membership_path(:person_id => params[:person_id],
                                                           :status => params[:status], :q => params[:q]) }
    end
  end


  def destroy
    #'editor' of person or group can destroy a membership
    permit "editor of Person or editor of Group"
    @membership = Membership.find(params[:id])
    @membership.destroy if @membership
    respond_to do |format|
      format.html do
        if @membership
          redirect_to new_person_membership_path(:person_id => @membership.person.id)
        else
          redirect_to root_url
        end
      end
    end

  end

  def ajax_sort
    ids = params[:ids].collect { |id| id.split('_').last.to_i }
    @person.transaction do
      ids.each_with_index do |id, position|
        membership = @person.memberships.where(:group_id => id).first
        membership.position = position + 1
        membership.save
      end
    end
    respond_to do |format|
      format.html do
        render :nothing => true
      end
    end
  end

  #TODO - at least some of what this is supposed to do is superseded by ajax_sort. Is it used for anything else,
  #or can it and its route be removed?
  def sort
    @person.groups.each do |group|
      membership = Membership.find_by_person_id_and_group_id(@person.id, group.id)
      membership.position = params["current"].index(group.id.to_s)+1
      membership.save
    end

    respond_to do |format|
      format.html { redirect_to new_membership_path(:person_id => @person.id) }
    end
  end


  def update
    membership = Membership.find(params[:id])
    fix_date_parameters
    membership.update_attributes(params[:membership])
    @person = membership.person
    respond_to do |format|
      format.html { render :partial => 'group', :collection => @person.groups(true) }
      format.js {render :nothing => true}
    end
  end

  private
  def find_person
    @person = Person.find_by_id(params[:person_id])
  end

  def find_group
    @group = Group.find_by_id(params[:group_id])
  end

  def find_membership
    @membership = Membership.find_by_person_id_and_group_id(params[:person_id], params[:group_id])
  end

#for the membership update we're having problems when a non-nil date is updated to be
#blank, which appears to be caused by how Rails handles date through the date-select
#helper and subsequent model side processing. This is to fix that. If a year field
#is blank, we delete all of the partial fields and replace with a whole field set
#to nil
  def fix_date_parameters
    ['start_date', 'end_date'].each do |date_field|
      if params[:membership]["#{date_field}(1i)"].blank?
        params[:membership].keys.select { |k| k.match(/^#{date_field}/) }.each do |key|
          params[:membership].delete(key)
        end
        params[:membership][date_field] = nil
      end
    end
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper

  def person_link(person)
    link_to(h(person.display_name), person_path(person))
  end

end

app/views/memberships/_action_links.html.haml
%ul.actions.clear-both
  %li=link_to_unless((@status.downcase == "member"), "#{Membership.model_name.human_pl} (#{@person.groups.count})",
      new_membership_url(:person_id => @person.id, :status => 'member'))
  |
  %li=link_to_unless((!defined?(@query) && @status.downcase == "non_member"), "#{t('.all_groups')} (#{Group.count})",
      new_membership_url(:person_id => @person.id, :status => 'non_member'))

app/views/memberships/_body_leftbar.html.haml
#picture.span-3
  %p= render "shared/person_image", :o => @person

%h3 #{Group.model_name.human_pl} (#{@person.groups.size})
%ol.groups_alphabetical
  - @person.groups.each do |g|
    %li #{link_to "#{g.name}", group_path(g)}

app/views/memberships/_group.html.haml
-include_stylesheets('specific/memberships/_group', 'specific/memberships/_group_list_item')
-membership = Membership.find_by_person_id_and_group_id(@person.id, group.id)
%li{ :id => "group_#{group.id}"}
  %strong
    %font{:size => '3'}
      = group.name
    %font{:size => '1'}
      = link_to t('.leave'), membership_url(membership), :confirm => t('.confirm'), :method => :delete

  %div.membership-group-form
    = form_for  membership, :as => :membership, :url => membership_url(membership), :remote => true, :html => {:method => :put} do |form|
      #{t 'app.title'}
      = form.text_field :title
      #{t '.year_joined'}:
      = form.date_select 'start_date', :start_year => 1950, :end_year => Time.now.year, :discard_month => true, :include_blank => true
      #{t '.year_left'}:
      = form.date_select 'end_date', :start_year => 1950, :end_year => Time.now.year, :discard_month => true, :include_blank => true
      %br/
      = submit_tag t('app.save')

app/views/memberships/_group_list.html.haml
- include_javascript('specific/memberships/_group_list')
#groups
  %ul
    = render :partial => 'group_list_item', :collection => @parents

app/views/memberships/_group_list_item.html.haml
- if !group_list_item.hide?
  - # only show groups that are in the @groups list
  - if @groups.include?(group_list_item)
    %li.parent.list-style-none
      .membership-group{:id => "group_id-#{group_list_item.id}"}
        - if group_list_item.children.empty?
          &nbsp;&nbsp;
        - else
          %a.toggle-switch{:'data-item-id' => group_list_item.id, :href => 'javascript:void(0)'} #{@query.blank? ? '+' : '-'}
        - parent_id = group_list_item.parent.nil? ? nil : group_list_item.parent.id
        - if @person.groups.include?(group_list_item)
          = check_box_tag "group_id[].ignore", "#{group_list_item.id}", true, {:disabled => true}
        - else
          = check_box_tag "group_id[]", "#{group_list_item.id}", false, {:'data-parent-id' => parent_id, :class => 'group-checkbox'}
        = group_list_item.name

      - unless group_list_item.children.empty?
        %ul#children_of.children.list-style-none{:id => group_list_item.id, :style => @query.if_blank("display: none;")}
          = render :partial => 'group_list_item', :collection => group_list_item.children

app/views/memberships/_join_groups_form.html.haml
= form_tag create_multiple_memberships_url, :method => :put, :name => "memberships_form", :id => "memberships_form" do
  %div
    #bulk_links
      = submit_tag t('.submit')

      = hidden_field_tag "person_id", @person.id
      = hidden_field_tag "status", @status
      -#Authenticity token is necessary so that Rails doesn't think this request is fraudulent (when someone clicks "delete selected" link)
      = hidden_field_tag "authenticity_token", form_authenticity_token
  .clear-both
  = render "group_list"

app/views/memberships/_member_groups.html.haml
- include_javascript('specific/memberships/_member_groups')
#edit_membership_active
  %ol#current
    = render :partial => "group", :collection => @person.groups(true).order(:position)
= hidden_field_tag('sort_url', ajax_sort_memberships_path)
= hidden_field_tag('person_id', @person.id)

app/views/memberships/_non_member_groups.html.haml
- if @query.present?
  %h3
    #{t '.searching_for'}
    = @query
    = link_to fugue_icon_tag('cross-button'), new_person_membership_path(:person_id => @person.id, :status => "non_member")
- if @groups.length < 1
  %p #{t '.no_groups'}
- else
  = render 'join_groups_form'

app/views/memberships/_search_form.html.haml
.span-8.attend-1.last.right
  = form_tag :action => "search_groups", :method => :get, :class => "memberships_search_form" do

    #search-box
      = text_field_tag(:q, nil, :size => 21)
      = hidden_field_tag "person_id", @person.id
      = hidden_field_tag "status", @status
      = submit_tag t('.submit')

app/views/memberships/new.html.haml
- include_stylesheet('specific/memberships/new')
- include_javascript('specific/memberships/new')
- if current_user_any_role?("editor", Group)
  = render :layout => '/layouts/admin_bar' do
    %li= link_to t('memberships.new.delete_person'), person_url(@person), :method => :delete, :confirm => t('memberships.new.delete_confirm')
    %li= link_to t('memberships.new.add_person'), new_person_path

= render :layout => '/layouts/main_body',
  :locals => {:header => "#{person_link(@person)}: #{Group.model_name.human_pl}".html_safe} do

  = render "shared/local_nav", :object => "person", :state => "edit"

  = render :partial => 'body_leftbar', :layout => 'layouts/main_body_left'

  %fieldset
    %legend #{t 'memberships.new.group_memberships'}
    .span-16.last.column
      - if @status == "non_member"
        = render :partial => 'search_form'
      = render "action_links"
      .span-15.append-1.last
        = render "#{@status}_groups"