config/routes.rb
Bibapp::Application.routes.draw do


  def make_routes
    resources :works do
      collection do
        get :auto_complete_for_author_string
        get :auto_complete_for_editor_string
        get :auto_complete_for_keyword_name
        get :auto_complete_for_publication_name
        get :auto_complete_for_publisher_name
        get :auto_complete_for_tag_name
        get :orphans
        delete :destroy_multiple
        #Following support legacy RJS stuff
        post :reorder_list
        post :add_item_to_list
        post :remove_item_from_list
        post :add_author_to_list
        post :remove_author_from_list
        post :add_contributor_to_list
        post :remove_contributor_from_list
        post :orphans_delete
      end
      member do
        get :merge_duplicates
        get :add_to_saved
        get :remove_from_saved
        put :change_type
      end

      resources :attachments
    end

    #####
    # Person routes
    #####
    resources :people do
      collection do
        get :batch_csv_show
        post :batch_csv_create
      end
      resources :attachments
      resources :works
      resources :groups
      resources :pen_names
      resources :memberships
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Group routes
    #####
    # Add Auto-Complete routes for adding new groups
    resources :groups do
      collection do
        get :auto_complete_for_group_name
        get :hidden
      end
      member do
        get :hide
        get :unhide
      end
      resources :works
      resources :people
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Membership routes
    #####
    # Add Auto-Complete routes
    resources :memberships do
      collection do
        get :auto_complete_for_group_name
        put :create_multiple
        post :sort
        post :search_groups
      end
    end

    #####
    # Contributorship routes
    #####
    resources :contributorships do
      collection do
        get :admin
        get :archivable
        put :act_on_multiple
      end

      member do
        put :verify
        put :deny
      end
    end
    #####
    # Publisher routes
    #####
    resources :publishers do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    #####
    # Publication routes
    #####
    resources :publications do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    ####
    # User routes
    ####
    # Make URLs like /user/1/password/edit for Users managing their passwords
    resources :users do
      resources :imports
      resource :password
      collection do
        match 'activate(/:activation_code)', :to => 'users#activate', :as => 'activate'
      end
      member do
        get :update_email
        post :request_update_email
      end
    end

    ####
    # Import routes
    ####
    resources :imports do
      resource :user
      resources :attachments
    end

    ####
    # Search route
    ####
    match 'search', :to => 'search#index', :as => 'search'
    match 'search/advanced', :to => 'search#advanced', :as => 'advanced_search'

    ####
    # Saved routes
    ####
    match 'saved', :to => 'user_sessions#saved', :as => 'saved'
    match 'sessions/delete_saved', :to => 'user_sessions#delete_saved',
          :as => 'delete_saved'
    match 'sessions/add_many_to_saved', :to => 'user_sessions#add_many_to_saved',
          :as => 'add_many_to_saved'
    ####
    # Authentication routes
    ####
    # Make easier routes for authentication (via restful_authentication)
    match 'signup', :to => 'users#new', :as => 'signup'
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'activate/:activation_code', :to => 'users#activate', :as => 'activate'

    ####
    # DEFAULT ROUTES
    ####
    # Install the default routes as the lowest priority.
    resources :name_strings
    resources :memberships
    resources :pen_names do
      collection do
        post :create_name_string
        post :live_search_for_name_strings
        post :sort
      end
    end
    resources :keywords
    resources :keywordings
    resources :passwords
    resources :attachments do
      collection do
        post :add_upload_box
      end
    end

    # Default homepage to works index action
    root :to => 'works#index'

    match 'citations', :to => 'works#index'

    resource :user_session

    resources :authentications
    match '/auth/:provider/callback' => 'authentications#create'
    match '/admin/index' => "admin#index"
    match 'admin/duplicates' => "admin#duplicates"
    match 'admin/ready_to_archive' => "admin#ready_to_archive"
    match 'admin/update_sherpa_data' => "admin#update_sherpa_data"
    match 'admin/deposit_via_sword' => "admin#deposit_via_sword"
    match 'admin/update_publishers_from_sherpa' => "admin#update_publishers_from_sherpa"

    match 'roles/index' => "roles#index"
    match 'roles/destroy' => "roles#destroy"
    match 'roles/create' => "roles#create"
    match 'roles/new_admin' => "roles#new_admin"
    match 'roles/new_editor' => "roles#new_editor"
  end

  if I18n.available_locales.many?
    locale_regexp = Regexp.new(I18n.available_locales.join('|'))
    scope "(:locale)", :locale => locale_regexp do
      make_routes
    end
    #uncomment to make multi-locale version able to direct locale-less routes as well
    #make_routes
  else
    make_routes
  end


end

app/views/admin/_dupes.html.haml
-#
-# Render List of Duplicate Works with paging & sorting options
-#
- include_stylesheet('specific/admin/_dupes')
- include_javascript('specific/admin/_dupes')
#works.span-17.last
  - if @q
    %div
      %h3= t('admin.duplicates.results', :count => @q.total_hits)

    / Sort Form
    .span-15.append-1.last
      = form_tag "#works", :name => "dupes_form_show_rows", :method => :get do
        #sort-by
          %label=t('app.show') + ":"
          %select{:name => "rows"}
            - ["10", "20", "50", "100", "250", "500"].each do |opt|
              %option{:value => "#{opt}", :selected => (opt == @rows ? 'selected' : nil)}= opt.titleize

          = render 'admin/dupes_hidden_tags'

          = submit_tag t('app.go')

      = form_tag destroy_multiple_works_url, :name => "dupes_form", :method => :delete, :id => "dupes_form" do
        #bulk_links
          = check_box_tag "select_dupes", "yes", false, :id => 'global-checkbox'
          %strong=t('app.select_all')

          = submit_tag t('app.delete_selected')
          = render 'admin/dupes_hidden_tags'

        %div= will_paginate WillPaginate::Collection.new((params[:page]||1), @rows, @q.total_hits)

        %ol#work-list.span-17.clear-both.no-padding-or-margin
          - @works.each do |work|
            = render "shared/work", :work => work, :allow_select => true, :show_status => true,
              :show_dupes => true, :links_array => [:edit]

        %div= will_paginate WillPaginate::Collection.new((params[:page]||1), @rows, @q.total_hits)

app/views/admin/_dupes_hidden_tags.html.haml
= hidden_field_tag "q", @query
= hidden_field_tag "fq", @filter_no_strip
= hidden_field_tag "view", "all"
- @page = 1 if @page == 0
= hidden_field_tag "page", @page
= hidden_field_tag "authenticity_token", form_authenticity_token
= hidden_field_tag "return_path" , admin_duplicates_url

app/views/admin/_groups_tasks.html.haml
%li=link_to t('common.groups.new'), new_group_path
%li=link_to t('common.groups.hidden'), hidden_groups_path

app/views/admin/_people_tasks.html.haml
%li=link_to t('common.people.new'), new_person_path
%li=link_to t('common.people.import_csv'), batch_csv_show_people_url

app/views/admin/_publications_tasks.html.haml
%li=link_to t('common.publications.new'), new_publication_path
%li=link_to t('common.publications.authority'), authorities_publications_path

app/views/admin/_publishers_tasks.html.haml
%li=link_to t('common.publishers.new'), new_publication_path
%li=link_to t('common.publishers.authority'), authorities_publishers_path
%li=link_to link_to t('common.publishers.sherpa'), admin_update_sherpa_data_url

app/views/admin/_users_tasks.html.haml
%li=link_to t('common.users.new'), new_user_url
%li=link_to t('common.users.show_all'), users_url
%li=link_to t('common.users.role'), roles_index_url

app/views/admin/_works.html.haml
%ol.works.facets
  - @works.each do |doc|
    %li
      =link_to doc.title_primary, work_path(doc)
      %p
        %strong NameStrings:
        - doc.name_strings.each do |ns|
          =link_to ns.name, name_string_path(ns)
        %br/
        %strong #{t('app.source')}:
        =link_to doc.publication.authority.name, publication_path(doc.publication.authority.to_param)
        = "#{doc.volume}(#{doc.issue}), #{doc.start_page}-#{doc.end_page}."
        -if doc.publication_date_year
          %br/
          %strong #{t('app.year')}:
          = doc.publication_date_year

app/views/admin/_works_tasks.html.haml
%li=link_to t('common.works.new'), new_user_import_path(current_user)
%li=link_to t('common.contributorships.verify'), admin_contributorships_path
%li=link_to t('common.works.duplicate'), admin_duplicates_url
%li=link_to t('app.archive'), admin_ready_to_archive_url
%li=link_to t('app.imports'), user_imports_path(@current_user)

app/views/admin/deposit_via_sword.html.haml
= render :layout => '/layouts/main_body', :locals => {:header => t('admin.deposit.header')} do
  - if @deposit
    %p.success #{t('admin.deposit.success')}
    %fieldset
      %legend #{t('admin.deposit.information')}
      .field
        %label #{t('admin.deposit.title')}:
        %span.field_value=@deposit['title']
      .field
        %label #{t('admin.deposit.uri')}:
        %span.field_value
          =link_to @deposit['id'], @deposit['id']
      .field
        %label #{t('admin.deposit.treatment')}:
        %span.field_value=@deposit['treatment']
      .field
        %label #{t('admin.deposit.repository')}:
        %span.field_value
          =link_to "#{t('personalize.repository_name')}", $REPOSITORY_BASE_URL
      .field
        %label #{t('admin.deposit.date')}:
        %span.field_value=@deposit['updated']
  = link_to t('admin.deposit.return'), work_path(@work)

app/views/admin/duplicates.html.haml
= render :layout => '/layouts/main_body', :locals => {:header => @title} do
  #results.span-22
    = render "shared/facets"
    / Works
    = render "dupes"

app/views/admin/index.html.haml
= render :layout => '/layouts/main_body', :locals => {:header => "#{@title}:"} do
  = render "admin_nav"
  %ul#tasks
    = render "#{@tab_name}_tasks"

app/views/admin/ready_to_archive.html.haml
= render :layout => 'layouts/main_body',
  :locals => {:header => t('.ready', :count => @works.size)} do
  - if @works.size > 0
    = render "works"
  - else
    %p= t('.no_works')

app/views/admin/update_sherpa_data.html.haml
/ === Admin === Update SHERPA Data ===
/ Main
- @title = "Update SHERPA Data" # Specify text at end of HTML <title> tag
= render :layout => '/layouts/main_body', :locals => {:header => t('admin.sherpa.update')} do
  %p=t('admin.sherpa.info1')
  %p=t('admin.sherpa.info2')

  = button_to t('admin.sherpa.update'), :action => :update_publishers_from_sherpa