config/routes.rb
Bibapp::Application.routes.draw do


  def make_routes
    resources :works do
      collection do
        get :auto_complete_for_author_string
        get :auto_complete_for_editor_string
        get :auto_complete_for_keyword_name
        get :auto_complete_for_publication_name
        get :auto_complete_for_publisher_name
        get :auto_complete_for_tag_name
        get :orphans
        delete :destroy_multiple
        #Following support legacy RJS stuff
        post :reorder_list
        post :add_item_to_list
        post :remove_item_from_list
        post :add_author_to_list
        post :remove_author_from_list
        post :add_contributor_to_list
        post :remove_contributor_from_list
        post :orphans_delete
      end
      member do
        get :merge_duplicates
        get :add_to_saved
        get :remove_from_saved
        put :change_type
      end

      resources :attachments
    end

    #####
    # Person routes
    #####
    resources :people do
      collection do
        get :batch_csv_show
        post :batch_csv_create
      end
      resources :attachments
      resources :works
      resources :groups
      resources :pen_names
      resources :memberships
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Group routes
    #####
    # Add Auto-Complete routes for adding new groups
    resources :groups do
      collection do
        get :auto_complete_for_group_name
        get :hidden
      end
      member do
        get :hide
        get :unhide
      end
      resources :works
      resources :people
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Membership routes
    #####
    # Add Auto-Complete routes
    resources :memberships do
      collection do
        get :auto_complete_for_group_name
        put :create_multiple
        post :sort
        post :search_groups
      end
    end

    #####
    # Contributorship routes
    #####
    resources :contributorships do
      collection do
        get :admin
        get :archivable
        put :act_on_multiple
      end

      member do
        put :verify
        put :deny
      end
    end
    #####
    # Publisher routes
    #####
    resources :publishers do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    #####
    # Publication routes
    #####
    resources :publications do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    ####
    # User routes
    ####
    # Make URLs like /user/1/password/edit for Users managing their passwords
    resources :users do
      resources :imports
      resource :password
      collection do
        match 'activate(/:activation_code)', :to => 'users#activate', :as => 'activate'
      end
      member do
        get :update_email
        post :request_update_email
      end
    end

    ####
    # Import routes
    ####
    resources :imports do
      resource :user
      resources :attachments
    end

    ####
    # Search route
    ####
    match 'search', :to => 'search#index', :as => 'search'
    match 'search/advanced', :to => 'search#advanced', :as => 'advanced_search'

    ####
    # Saved routes
    ####
    match 'saved', :to => 'user_sessions#saved', :as => 'saved'
    match 'sessions/delete_saved', :to => 'user_sessions#delete_saved',
          :as => 'delete_saved'
    match 'sessions/add_many_to_saved', :to => 'user_sessions#add_many_to_saved',
          :as => 'add_many_to_saved'
    ####
    # Authentication routes
    ####
    # Make easier routes for authentication (via restful_authentication)
    match 'signup', :to => 'users#new', :as => 'signup'
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'activate/:activation_code', :to => 'users#activate', :as => 'activate'

    ####
    # DEFAULT ROUTES
    ####
    # Install the default routes as the lowest priority.
    resources :name_strings
    resources :memberships
    resources :pen_names do
      collection do
        post :create_name_string
        post :live_search_for_name_strings
        post :sort
      end
    end
    resources :keywords
    resources :keywordings
    resources :passwords
    resources :attachments do
      collection do
        post :add_upload_box
      end
    end

    # Default homepage to works index action
    root :to => 'works#index'

    match 'citations', :to => 'works#index'

    resource :user_session

    resources :authentications
    match '/auth/:provider/callback' => 'authentications#create'
    match '/admin/index' => "admin#index"
    match 'admin/duplicates' => "admin#duplicates"
    match 'admin/ready_to_archive' => "admin#ready_to_archive"
    match 'admin/update_sherpa_data' => "admin#update_sherpa_data"
    match 'admin/deposit_via_sword' => "admin#deposit_via_sword"
    match 'admin/update_publishers_from_sherpa' => "admin#update_publishers_from_sherpa"

    match 'roles/index' => "roles#index"
    match 'roles/destroy' => "roles#destroy"
    match 'roles/create' => "roles#create"
    match 'roles/new_admin' => "roles#new_admin"
    match 'roles/new_editor' => "roles#new_editor"
  end

  if I18n.available_locales.many?
    locale_regexp = Regexp.new(I18n.available_locales.join('|'))
    scope "(:locale)", :locale => locale_regexp do
      make_routes
    end
    #uncomment to make multi-locale version able to direct locale-less routes as well
    #make_routes
  else
    make_routes
  end


end

app/models/group.rb
require 'machine_name'
require 'stop_word_name_sorter'
require 'solr_helper_methods'
require 'solr_updater'

class Group < ActiveRecord::Base
  include MachineNameUpdater
  include SolrHelperMethods
  include SolrUpdater
  include StopWordNameSorter

  acts_as_tree :order => "name"
  acts_as_authorizable #some actions on groups require authorization

  #### Associations ####

  has_many :people,
           :through => :memberships,
           :order => "last_name, first_name"
  has_many :memberships

  scope :hidden, where(:hide => true)
  scope :unhidden, where(:hide => false)
  scope :sort_name_like, lambda {|name| where('sort_name like ?', name.downcase)}
  scope :name_like, lambda { |name| where('name like ?', name) }
  scope :order_by_name, order('name')
  #### Callbacks ####

  before_save :update_machine_name
  before_save :update_sort_name

  # return the first letter of each name, ordered alphabetically
  def self.letters
    self.unhidden.select('DISTINCT SUBSTR(name, 1, 1) AS letter').order('letter').collect {|x| x.letter.upcase}
  end

  #Parse Solr data (produced by to_solr_data)
  # return Group name and ID
  def self.parse_solr_data(group_data)
    data = group_data.split("||")
    name = data[0]
    id = data[1].strip

    return name, id
  end

  #### Methods ####

  def works
    self.people.collect {|p| p.works.verified}.flatten.uniq
  end

  def get_associated_works
    self.works
  end

  def require_reindex?
    self.name_changed? or self.machine_name_changed? or self.hide_changed?
  end

  # Convert object into semi-structured data to be stored in Solr
  def to_solr_data
    "#{name}||#{id}"
  end

  def solr_filter
    %Q(group_id:"#{self.id}")
  end

  #Add an http:// if this (or https://) isn't found before the url
  #hoped to be able to use URI to do this more nicely, but haven't figured it out yet
  def canonicalize_url
    uri = URI.parse(self.url)
    return self.url if ['http', 'https'].include?(uri.scheme)
    return 'http://' + self.url
  rescue URI::InvalidURIError
    return "#"
  end

  #TODO acts_as_tree isn't really all that great, and we may want to replace it sometime
  #Note that it provides methods: parent, children, siblings, self_and_siblings,
  #ancestors, and root. As an example, we might use a nested_set gem (maybe better_nested_set)). It should
  #almost drop in - create the columns lft/rgt in a migration, put acts_as_nested_set
  #in the class definition, and run renumber_full_tree to generate the left/right indexes.

  #Return the group's top-level parent (ancestor)
  def top_level_parent
    self.root
  end

  def ancestors_and_descendants
    self.ancestors + self.descendants
  end

  def descendants
    self.children.map(&:descendants).flatten + self.children
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GoogleChartsHelper
  include KeywordCloudHelper

  #Require a user be logged in to create / update / destroy
  before_filter :login_required, :only => [:new, :create, :edit, :update, :destroy, :hide]

  make_resourceful do
    build :all

    publish :xml, :json, :yaml, :attributes => [
        :id, :name, :url, :description,
        {:people => [:id, :name]}
    ]

    #Add a response for RSS
    response_for :show do |format|
      format.html #loads show.html.haml (HTML needs to be first, so I.E. views it by default)
      format.rss #loads show.rss.rxml
    end

    before :index do
      @title = Group.model_name.human_pl
      # find first letter of group names (in uppercase, for paging mechanism)
      @a_to_z = Group.letters

      if params[:person_id]
        @person = Person.find(params[:person_id].split("-")[0])

        # Collect a list of the person's top-level groups for the tree view
        @top_level_groups = Array.new
        @person.memberships.active.select { |m| !m.group.hide? }.each do |m|
          @top_level_groups << m.group.top_level_parent
        end
        @top_level_groups.uniq!
      end

      @page = params[:page] || @a_to_z[0]
      @current_objects = Group.unhidden.sort_name_like("#{@page}%").order(:sort_name)
    end

    before :show do
      search(params)
      @group = @current_object
      @title = @group.name
      work_count = @q.data['response']['numFound']

      if work_count > 0
        @chart_url = google_chart_url(@facets, work_count)
        @keywords = set_keywords(@facets)
      end
    end

    before :new do
      @groups = Group.unhidden.order_by_name
    end


    before :edit do
      #'editor' of group can edit that group
      #permit "editor of group"

      @groups = Group.unhidden.order_by_name
    end
  end

  def create

    @duplicategroup = Group.name_like(params[:group][:name]).first

    if @duplicategroup.nil?
      @group = Group.find_or_create_by_name(params[:group])
      @group.hide = false
      @group.save

      respond_to do |format|
        flash[:notice] = t('common.groups.flash_create_success')
        format.html { redirect_to group_url(@group) }
      end
    else
      respond_to do |format|
        flash[:notice] = t('common.groups.flash_create_duplicate')
        format.html { redirect_to new_group_path }
      end
    end
  end

  def hidden
    @hidden_groups = Group.hidden.order(:sort_name)
    @title = t('common.groups.hidden_groups')
  end

  def autocomplete
    respond_to do |format|
      format.json {render :json => json_name_search(params[:term].downcase, Group, 8)}
    end
  end

  def hide
    @group = Group.find(params[:id])

    permit "editor on group"

    children = @group.children.select { |c| !c.hide? }

    # don't hide groups with children
    if children.blank?
      @group.hide = true
      @group.save
      respond_to do |format|
        flash[:notice] = t('common.groups.flash_hide_success')
        format.html { redirect_to :action => "index" }
      end
    else
      respond_to do |format|
        flash[:error] = t('common.groups.flash_hide_failure_html', :children => child_list(children))
        format.html { redirect_to :action => "edit" }
      end
    end
  end

  def unhide
    @group = Group.find(params[:id])

    permit "editor on group"

    parent = @group.parent

    if parent.hide?
      respond_to do |format|
        flash[error] = t('common.groups.flash_unhide_failure_html', :parent_name => parent.name)
        format.html { redirect_to :action => "edit" }
      end

    end
    @group.hide = false
    @group.save
    respond_to do |format|
      flash[:notice] = t('common.groups.flash_unhide_success')
      format.html { redirect_to :action => "index" }
    end
  end

  def destroy
    permit "admin"

    @group = Group.find(params[:id])

    #check memberships
    memberships = @group.memberships

    #check children
    children = @group.children

    if memberships.blank? and children.blank?
      @group.destroy
      respond_to do |format|
        flash[:notice] = t('common.groups.flash_destroy_success')
        format.html { redirect_to groups_path() }
      end
    elsif !memberships.blank?
      respond_to do |format|
        flash[:error] = t('common.groups.flash_destroy_failure_memberships')
        format.html { redirect_to :action => "edit" }
      end
    elsif children.present?
      respond_to do |format|
        flash[:error] = t('common.groups.flash_destroy_failure_children_html', :child_list => child_list(children))
        format.html { redirect_to :action => "edit" }
      end
    end
  end

  protected

  def child_list(children)
    items = children.collect {|c| "<li>#{c.name}</li>"}
    "<ul>#{items.join('')}</ul>"
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def body_header(group)
    (group.name + link_to(fugue_icon_tag('feed'), group_path(@group, :format => "rss"))).html_safe
  end

  def parent_link(group)
    group.parent ? link_to(group.parent.name, group.parent) : ''
  end

end

app/views/groups/_complete_index.html.haml
- if current_user_any_role?("editor", Group)
  = render :layout => 'layouts/admin_bar' do
    %li= link_to t('groups.complete_index.add_group'), new_group_path
    - if logged_in? && current_user.has_role?("admin", System)
      %li= link_to t('groups.complete_index.show_hidden'), hidden_groups_path

= render :layout => 'layouts/main_body_no_h2'  do
  %h2 #{Group.model_name.human_pl}

  = render "shared/alpha_pagination"

  = render 'group_table', :groups => @current_objects

  %br/
  %br/
  = render "shared/alpha_pagination"

app/views/groups/_form.html.haml
- include_javascript('specific/groups/_form')
%fieldset
  %legend #{Group.model_name.human}
  %p
    %label #{t('app.name')}
    %br/
    = text_field :group, :name
  %p
    %label #{t('app.description')}
    %br/
    = form.text_area :description
  %p
    %label #{t('app.url')}
    %br/
    = form.text_field :url
  %p
    %label #{t('.parent_group')}
    %br/
    = form.collection_select :parent_id, @groups, :id, :name, :include_blank => true
  %p.submit
    = submit_tag t('app.save')

app/views/groups/_group_table.html.haml
%table#groups
  %tr
    %th.span-10 #{t('.group_name')}
    %th.span-10 #{t('.parent_group')}
    %th.span-2.last #{t('.members')}
  - groups.each do |group|
    %tr{:class => cycle("even", "odd")}
      %td= link_to group.name, group
      %td= parent_link(group)
      %td= group.memberships.length

app/views/groups/_person_index.html.haml
- if logged_in? && current_user.has_role?("editor", Person.find(params[:person_id]))
  = render :partial => "people/admin_actions", :layout => 'layouts/admin_bar'

= render :layout => 'layouts/main_body_no_h2'  do
  .span-5
    .text-center
      #{image_tag(@person.image_url, :class => 'group-index-person-image', :size => "75x100")}

  %div.span-17.last
    %h2
      #{link_to(h(@person.display_name), person_path(@person)).html_safe}
    = render "shared/local_nav", :object => "person"

    = render 'shared/group_list'

app/views/groups/_recent_works_box.html.haml
%h3.heading
  =link_to t('.recent_works'), group_works_path(@group)
%ol#works.span-7.works
  - @works.first(3).each do |work|
    = render "shared/work", :work => work

app/views/groups/_related_groups_box.html.haml
- unless @group.parent.nil? or @group.parent.hide?
  %h3.heading #{t('.belongs_to')}
  %ul.parent-group
    %li= link_to @group.parent.name, group_path(@group.parent)
- unless @group.children.empty?
  %h3.heading #{t('.subgroups')}
  %ul.sub-groups
    -@group.children.each do |g|
      - unless g.hide?
        %li
          =link_to g.name, group_path(g)
          ="(#{g.works.count})"

app/views/groups/_work_types_box.html.haml
%h3 #{t('.types_of_work')}
.text-center
  %img{:src => "#{@chart_url}", :class => 'group-show-chart-image'}

app/views/groups/edit.html.haml
- if current_user_role?("editor", @group)
  = render :layout => 'layouts/admin_bar' do
    - if logged_in? && current_user.has_role?("editor", @group)
      - if @group.hide == true
        %li= link_to t('groups.edit.unhide'), unhide_group_url(@group), :confirm => t('app.are_you_sure')
      - else
        %li= link_to t('groups.edit.hide'), hide_group_url(@group), :confirm => t('app.are_you_sure')
    - if logged_in? && current_user.has_role?("admin", @group)
      %li= link_to t('groups.edit.delete'), group_url(@group), :method => :delete, :confirm => t('groups.edit.delete_confirm')

  .span-22.prepend-1

    %h2 #{t('.header_html', :link_to_group => link_to(h(@group.name), group_path(@group)))}

    .span-16.column
      = form_for @group, :as => :group, :url => group_path(@group), :html => {:method => :put} do |form|
        = render 'form', :form => form

app/views/groups/hidden.html.haml
- if current_user_role?("editor", System)
  = render :layout => 'layouts/main_body', :locals => {:header => t('groups.hidden.header')} do

    - if @hidden_groups.empty?
      %p #{t('groups.hidden.empty')}

    = render 'group_table', :groups => @hidden_groups

    %br/
    %br/

app/views/groups/index.html.haml
- include_stylesheet('specific/groups/index')

- if params[:person_id]
  = render 'person_index'
- else
  = render 'complete_index'

app/views/groups/new.html.haml
= render :layout => 'layouts/main_body', :locals => {:header => t('groups.new.header')} do
  = form_for @group, :as => :group, :url => groups_url, :html => {:method => :post} do |form|
    = render 'form', :form => form

app/views/groups/show.html.haml
- include_stylesheet('specific/groups/show')

- if current_user_role?("editor", @group)
  = render :layout => 'layouts/admin_bar' do
    %li= link_to t('groups.show.add'), new_group_path
    %li= link_to t('groups.show.edit'), edit_group_path
    %li= link_to t('groups.show.roles'), group_roles_path(@group)

= render :layout => 'layouts/main_body', :locals => {:header => body_header(@group)} do
  = render "shared/local_nav", :object => "group"

.span-15.prepend-1
  = render "shared/people", :count => 15, :randomize => true

  .span-14
    %h3.heading #{t('app.description')}
    %p= @group.description
    - if @group.url.present?
      %p= link_to h(@group.url), @group.canonicalize_url

    .span-6.append-2
      = render "shared/publications", :count => 10

    .span-6.last
      = render "shared/publishers", :count => 10


.span-7.last
  = render :partial => 'related_groups_box', :layout => 'layouts/right_box_no_border'
  = render :partial => 'work_types_box', :layout => 'layouts/right_box_no_border'
  = render :partial => "shared/keyword_cloud", :layout => 'layouts/right_box_no_border', :locals => {:keywords => @keywords, :id => 'tagcloud'}
  = render :partial => 'recent_works_box', :layout => 'layouts/right_box_no_border'