config/routes.rb
Bibapp::Application.routes.draw do


  def make_routes
    resources :works do
      collection do
        get :auto_complete_for_author_string
        get :auto_complete_for_editor_string
        get :auto_complete_for_keyword_name
        get :auto_complete_for_publication_name
        get :auto_complete_for_publisher_name
        get :auto_complete_for_tag_name
        get :orphans
        delete :destroy_multiple
        #Following support legacy RJS stuff
        post :reorder_list
        post :add_item_to_list
        post :remove_item_from_list
        post :add_author_to_list
        post :remove_author_from_list
        post :add_contributor_to_list
        post :remove_contributor_from_list
        post :orphans_delete
      end
      member do
        get :merge_duplicates
        get :add_to_saved
        get :remove_from_saved
        put :change_type
      end

      resources :attachments
    end

    #####
    # Person routes
    #####
    resources :people do
      collection do
        get :batch_csv_show
        post :batch_csv_create
      end
      resources :attachments
      resources :works
      resources :groups
      resources :pen_names
      resources :memberships
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Group routes
    #####
    # Add Auto-Complete routes for adding new groups
    resources :groups do
      collection do
        get :auto_complete_for_group_name
        get :hidden
      end
      member do
        get :hide
        get :unhide
      end
      resources :works
      resources :people
      resources :roles do
        collection do
          get :new_admin
          get :new_editor
        end
      end
      resources :keywords do
        collection do
          get :timeline
        end
      end
    end

    #####
    # Membership routes
    #####
    # Add Auto-Complete routes
    resources :memberships do
      collection do
        get :auto_complete_for_group_name
        put :create_multiple
        post :sort
        post :search_groups
      end
    end

    #####
    # Contributorship routes
    #####
    resources :contributorships do
      collection do
        get :admin
        get :archivable
        put :act_on_multiple
      end

      member do
        put :verify
        put :deny
      end
    end
    #####
    # Publisher routes
    #####
    resources :publishers do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    #####
    # Publication routes
    #####
    resources :publications do
      collection do
        get :authorities
        put :update_multiple
        get :add_to_box
        get :remove_from_box
      end
    end

    ####
    # User routes
    ####
    # Make URLs like /user/1/password/edit for Users managing their passwords
    resources :users do
      resources :imports
      resource :password
      collection do
        match 'activate(/:activation_code)', :to => 'users#activate', :as => 'activate'
      end
      member do
        get :update_email
        post :request_update_email
      end
    end

    ####
    # Import routes
    ####
    resources :imports do
      resource :user
      resources :attachments
    end

    ####
    # Search route
    ####
    match 'search', :to => 'search#index', :as => 'search'
    match 'search/advanced', :to => 'search#advanced', :as => 'advanced_search'

    ####
    # Saved routes
    ####
    match 'saved', :to => 'user_sessions#saved', :as => 'saved'
    match 'sessions/delete_saved', :to => 'user_sessions#delete_saved',
          :as => 'delete_saved'
    match 'sessions/add_many_to_saved', :to => 'user_sessions#add_many_to_saved',
          :as => 'add_many_to_saved'
    ####
    # Authentication routes
    ####
    # Make easier routes for authentication (via restful_authentication)
    match 'signup', :to => 'users#new', :as => 'signup'
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'activate/:activation_code', :to => 'users#activate', :as => 'activate'

    ####
    # DEFAULT ROUTES
    ####
    # Install the default routes as the lowest priority.
    resources :name_strings
    resources :memberships
    resources :pen_names do
      collection do
        post :create_name_string
        post :live_search_for_name_strings
        post :sort
      end
    end
    resources :keywords
    resources :keywordings
    resources :passwords
    resources :attachments do
      collection do
        post :add_upload_box
      end
    end

    # Default homepage to works index action
    root :to => 'works#index'

    match 'citations', :to => 'works#index'

    resource :user_session

    resources :authentications
    match '/auth/:provider/callback' => 'authentications#create'
    match '/admin/index' => "admin#index"
    match 'admin/duplicates' => "admin#duplicates"
    match 'admin/ready_to_archive' => "admin#ready_to_archive"
    match 'admin/update_sherpa_data' => "admin#update_sherpa_data"
    match 'admin/deposit_via_sword' => "admin#deposit_via_sword"
    match 'admin/update_publishers_from_sherpa' => "admin#update_publishers_from_sherpa"

    match 'roles/index' => "roles#index"
    match 'roles/destroy' => "roles#destroy"
    match 'roles/create' => "roles#create"
    match 'roles/new_admin' => "roles#new_admin"
    match 'roles/new_editor' => "roles#new_editor"
  end

  if I18n.available_locales.many?
    locale_regexp = Regexp.new(I18n.available_locales.join('|'))
    scope "(:locale)", :locale => locale_regexp do
      make_routes
    end
    #uncomment to make multi-locale version able to direct locale-less routes as well
    #make_routes
  else
    make_routes
  end


end

app/models/name_string.rb
require 'lib/machine_name'
require 'namecase'

class NameString < ActiveRecord::Base
  include MachineName

  #### Associations ####
  has_many :works, :through => :work_name_strings
  has_many :work_name_strings, :dependent => :destroy
  has_many :people, :through => :pen_names
  has_many :pen_names

  #### Callbacks ####

  #### Named Scopes ####
  scope :order_by_name, order('name')
  scope :name_like, lambda { |name| where('name like ?', "%#{name}%") }

  before_save :update_machine_name

  # return the first letter of each name, ordered alphabetically
  def self.letters
    self.select('DISTINCT SUBSTR(name, 1, 1) AS letter').order('letter').collect {|x| x.letter}
  end

  #Parse Solr data (produced by to_solr_data)
  # return NameString name and ID
  def self.parse_solr_data(name_string_data)
    data = name_string_data.split("||")
    name = data[0]
    id = data[1]

    return name, id
  end

# Convert object into semi-structured data to be stored in Solr
  def to_solr_data
    "#{name}||#{id}"
  end

  def to_param
    param_name = name.gsub("-", "_")
    param_name.gsub!(/[^A-Za-z0-9_]/, "")
    "#{id}-#{param_name}"
  end

  #return what looks to be the last name in this name string
  def last_name
    self.name.split(',').first
  end

  def update_machine_name
    self.machine_name = make_machine_name(self.name) if self.name_changed?
  end
end

app/controllers/name_strings_controller.rb
class NameStringsController < ApplicationController

  #Require a user be logged in to create / update / destroy
  before_filter :login_required, :only => [:new, :create, :edit, :update, :destroy]

  make_resourceful do
    build :all

    before :index do
      @a_to_z = NameString.letters

      @page = params[:page] || @a_to_z[0]
      @current_objects = NameString.where("upper(name) like ?", "#{@page}%").order('upper(name)')
    end

    response_for :index do |format|
      format.html # index.html
      format.xml { render :xml => @name_strings.to_xml }
    end

    before :show do

    end

    response_for :show do |format|
      format.html # index.html
      format.xml { render :xml => @name_string.to_xml }
    end
  end

  def autocomplete
    respond_to do |format|
      format.json {render :json => json_name_search(params[:term].downcase, NameString, 8)}
    end
  end

end

app/helpers/name_strings_helper.rb
module NameStringsHelper
  def person_image(person)
    image_tag(person.image_url, :class => 'person-photo', :size => "75x100",
              :alt => person.display_name, :title => person.display_name)
  end
end

app/views/name_strings/_actions.html.haml
%ul.actions
  %li= link_to t('app.show'), name_string_path(ns)
  %li= link_to t('app.edit'), edit_name_string_path(ns)
  %li= link_to t('app.destroy'), {:controller=>"name_strings", :action=>"destroy", :id=>ns.id}, :confirm => t('app.are_you_sure'), :method => :delete

app/views/name_strings/_form.html.haml
%fieldset
  %legend #{NameString.model_name.human_pl}
  = form_for @name_string do |form|
    %p
      %label #{t 'app.name'}
      %br/
      = form.text_field :name
      = form.hidden_field :cleaned, :value => true
    %p.submit
      = submit_tag :save

app/views/name_strings/edit.html.haml
= render :partial => 'form', :layout => 'layouts/main_body',
  :locals => {:header => t('.header', :name => @current_object.name)}

app/views/name_strings/index.html.haml
- if current_user_any_role?("editor", Group)
  = render :layout => 'layouts/admin_bar' do
    %li= link_to t('name_strings.index.add'), new_name_string_path

= render :layout => 'layouts/main_body', :locals => {:header => "#{NameString.model_name.human_pl} (#{@page})"} do
  = render "shared/alpha_pagination"

  %ol#name_strings
    -@current_objects.each do |name_string|
      %li.name_string
        = link_to name_string.name, name_string_path(name_string)

app/views/name_strings/new.html.haml
%h3 #{t '.header'}
= render :partial => 'form'

app/views/name_strings/show.html.haml
- include_stylesheet('specific/name_strings/show')
- if current_user_any_role?("editor", Group)
  = render :layout => 'layouts/admin_bar' do
    %li #{link_to t('name_strings.show.edit_link'), edit_name_string_path(@name_string)}

= render :layout => 'layouts/main_body_no_h2' do
  %h2
    #{t 'app.name'}:
    %strong #{@name_string.name}

  .span-23
    - if @name_string.people.size > 0
      %h4 #{t 'name_strings.show.have_published'}:
      %ol.people
        -@name_string.people.each do |person|
          %li.inline.no-padding-or-margin
            .span-3
              = link_to(person_image(person), person_path(person))
              .person-info
                %strong #{person.works.size}
                %h7 #{link_to person.last_name, person_path(person)}
    - else
      %p #{t 'name_strings.show.no_claim', :university_name => t('personalize.university_short_name')}